import 'daily_mission.dart';

class MissionData {
  static List<DailyMission> get all30DayMissions => [
        // Week 1 (Day 1-7): 세부 프로필
        DailyMission(
          day: 1,
          category: '세부 프로필',
          title: 'MBTI',
          question: 'MBTI가 무엇인가요?',
          type: MissionType.choice,
          choices: [
            'ISTJ', 'ISFJ', 'INFJ', 'INTJ',
            'ISTP', 'ISFP', 'INFP', 'INTP',
            'ESTP', 'ESFP', 'ENFP', 'ENTP',
            'ESTJ', 'ESFJ', 'ENFJ', 'ENTJ',
            '모름'
          ],
          rewardTrustScore: 1,
          icon: '🧠',
        ),
        DailyMission(
          day: 2,
          category: '세부 프로필',
          title: '혈액형',
          question: '혈액형은 무엇인가요?',
          type: MissionType.choice,
          choices: ['A형', 'B형', 'O형', 'AB형', '모름'],
          rewardTrustScore: 1,
          icon: '🩸',
        ),
        DailyMission(
          day: 3,
          category: '세부 프로필',
          title: '흡연',
          question: '흡연을 하시나요?',
          type: MissionType.choice,
          choices: ['비흡연', '가끔', '흡연'],
          rewardTrustScore: 1,
          icon: '🚭',
        ),
        DailyMission(
          day: 4,
          category: '세부 프로필',
          title: '음주',
          question: '음주는 어느 정도 하시나요?',
          type: MissionType.choice,
          choices: ['안 마심', '가끔', '자주', '매우 자주'],
          rewardTrustScore: 1,
          icon: '🍺',
        ),
        DailyMission(
          day: 5,
          category: '세부 프로필',
          title: '종교',
          question: '종교가 있으신가요?',
          type: MissionType.choice,
          choices: ['무교', '기독교', '천주교', '불교', '기타'],
          rewardTrustScore: 1,
          icon: '🙏',
        ),
        DailyMission(
          day: 6,
          category: '세부 프로필',
          title: '체형',
          question: '체형은 어떻게 되시나요?',
          type: MissionType.choice,
          choices: ['마른', '슬림', '보통', '탄탄', '근육질', '통통'],
          rewardTrustScore: 1,
          icon: '💪',
        ),
        DailyMission(
          day: 7,
          category: '세부 프로필',
          title: '학력',
          question: '최종 학력은 어떻게 되시나요?',
          type: MissionType.choice,
          choices: ['고졸', '대학 재학', '대졸', '대학원 재학', '석사', '박사'],
          rewardTrustScore: 1,
          icon: '🎓',
        ),

        // Week 2 (Day 8-14): 라이프스타일
        DailyMission(
          day: 8,
          category: '라이프스타일',
          title: '취미',
          question: '어떤 취미가 있으신가요? (최대 3개)',
          type: MissionType.multiChoice,
          choices: [
            '운동', '독서', '영화/드라마', '음악', '게임',
            '요리', '여행', '사진', '그림', '악기'
          ],
          rewardTrustScore: 2,
          icon: '🎨',
        ),
        DailyMission(
          day: 9,
          category: '라이프스타일',
          title: '운동 빈도',
          question: '운동은 얼마나 자주 하시나요?',
          type: MissionType.choice,
          choices: ['안 함', '가끔 (월 1-2회)', '보통 (주 1-2회)', '자주 (주 3-4회)', '매일'],
          rewardTrustScore: 1,
          icon: '🏃',
        ),
        DailyMission(
          day: 10,
          category: '라이프스타일',
          title: '반려동물',
          question: '반려동물을 키우시나요?',
          type: MissionType.choice,
          choices: ['없음', '강아지', '고양이', '기타', '여러 마리'],
          rewardTrustScore: 1,
          rewardTemperature: 0.2,
          icon: '🐾',
        ),
        DailyMission(
          day: 11,
          category: '라이프스타일',
          title: '여행 스타일',
          question: '여행은 어떻게 즐기시나요?',
          type: MissionType.choice,
          choices: ['계획적', '즉흥적', '휴양', '액티비티', '문화탐방'],
          rewardTrustScore: 1,
          icon: '✈️',
        ),
        DailyMission(
          day: 12,
          category: '라이프스타일',
          title: '아침형/저녁형',
          question: '아침형 인간인가요, 저녁형 인간인가요?',
          type: MissionType.choice,
          choices: ['아침형', '중간', '저녁형', '올빼미형'],
          rewardTrustScore: 1,
          icon: '🌅',
        ),
        DailyMission(
          day: 13,
          category: '라이프스타일',
          title: '식사 스타일',
          question: '평소 식사는 어떻게 하시나요?',
          type: MissionType.choice,
          choices: ['집밥', '외식', '배달', '간편식', '다양하게'],
          rewardTrustScore: 1,
          icon: '🍽️',
        ),
        DailyMission(
          day: 14,
          category: '라이프스타일',
          title: '주말 활동',
          question: '주말은 주로 어떻게 보내시나요?',
          type: MissionType.multiChoice,
          choices: ['집에서 휴식', '운동', '친구 만남', '데이트', '문화생활', '여행', '취미 활동'],
          rewardTrustScore: 2,
          rewardTemperature: 0.3,
          icon: '🎈',
        ),

        // Week 3 (Day 15-21): 성격 & 가치관
        DailyMission(
          day: 15,
          category: '성격',
          title: '성격',
          question: '자신의 성격을 표현해주세요 (최대 3개)',
          type: MissionType.multiChoice,
          choices: [
            '외향적', '내향적', '활발한', '차분한', '유머러스',
            '진지한', '계획적', '즉흥적', '감성적', '이성적'
          ],
          rewardTrustScore: 2,
          rewardTemperature: 0.3,
          icon: '😊',
        ),
        DailyMission(
          day: 16,
          category: '성격',
          title: '갈등 해결',
          question: '갈등이 생기면 어떻게 해결하시나요?',
          type: MissionType.choice,
          choices: ['바로 대화', '시간 갖고 대화', '회피', '타협', '제3자 개입'],
          rewardTrustScore: 1,
          icon: '💬',
        ),
        DailyMission(
          day: 17,
          category: '성격',
          title: '스트레스 해소',
          question: '스트레스는 어떻게 푸시나요?',
          type: MissionType.multiChoice,
          choices: ['운동', '수면', '음식', '쇼핑', '여행', '취미', '대화'],
          rewardTrustScore: 1,
          icon: '😌',
        ),
        DailyMission(
          day: 18,
          category: '가치관',
          title: '가족관',
          question: '가족과의 관계는 어떠신가요?',
          type: MissionType.choice,
          choices: ['매우 친밀', '친밀', '보통', '독립적', '소원함'],
          rewardTrustScore: 1,
          icon: '👨‍👩‍👧',
        ),
        DailyMission(
          day: 19,
          category: '가치관',
          title: '일과 삶의 균형',
          question: '일과 삶의 균형을 어떻게 생각하시나요?',
          type: MissionType.choice,
          choices: ['일이 우선', '균형 중시', '삶이 우선', '상황에 따라'],
          rewardTrustScore: 1,
          icon: '⚖️',
        ),
        DailyMission(
          day: 20,
          category: '가치관',
          title: '돈에 대한 생각',
          question: '돈에 대한 당신의 생각은?',
          type: MissionType.choice,
          choices: ['저축형', '투자형', '소비형', '균형형'],
          rewardTrustScore: 1,
          icon: '💰',
        ),
        DailyMission(
          day: 21,
          category: '특별 미션',
          title: '3주 달성!',
          question: '지금까지의 소감을 한 줄로 말해주세요',
          placeholder: '자유롭게 작성해주세요',
          type: MissionType.text,
          rewardTrustScore: 3,
          rewardTemperature: 0.5,
          icon: '🎊',
        ),

        // Week 4+ (Day 22-30): 연애관 & 매칭 조건
        DailyMission(
          day: 22,
          category: '연애관',
          title: '연애 경험',
          question: '연애 경험이 어느 정도 되시나요?',
          type: MissionType.choice,
          choices: ['없음', '1번', '2-3번', '4-5번', '6번 이상'],
          rewardTrustScore: 1,
          icon: '💕',
        ),
        DailyMission(
          day: 23,
          category: '연애관',
          title: '연애 스타일',
          question: '어떤 연애 스타일인가요?',
          type: MissionType.multiChoice,
          choices: ['다정한', '열정적', '신중한', '솔직한', '배려하는', '독립적'],
          rewardTrustScore: 2,
          icon: '❤️',
        ),
        DailyMission(
          day: 24,
          category: '연애관',
          title: '이상형',
          question: '어떤 스타일을 선호하시나요?',
          type: MissionType.multiChoice,
          choices: ['다정한', '유머러스한', '지적인', '활발한', '차분한', '세심한'],
          rewardTrustScore: 2,
          rewardTemperature: 0.3,
          icon: '💖',
        ),
        DailyMission(
          day: 25,
          category: '매칭 조건',
          title: '나이 범위',
          question: '어떤 나이대를 선호하시나요?',
          type: MissionType.choice,
          choices: ['동갑', '±1살', '±2살', '±3살', '±5살', '상관없음'],
          rewardTrustScore: 1,
          icon: '🎯',
        ),
        DailyMission(
          day: 26,
          category: '매칭 조건',
          title: '거리',
          question: '어느 정도 거리까지 괜찮으신가요?',
          type: MissionType.choice,
          choices: ['같은 지역', '인접 지역', '같은 권역', '전국', '상관없음'],
          rewardTrustScore: 1,
          icon: '🗺️',
        ),
        DailyMission(
          day: 27,
          category: '데이트',
          title: '데이트 스타일',
          question: '어떤 데이트를 선호하시나요?',
          type: MissionType.multiChoice,
          choices: ['카페', '식사', '영화', '산책', '운동', '문화생활', '여행'],
          rewardTrustScore: 2,
          icon: '💑',
        ),
        DailyMission(
          day: 28,
          category: '데이트',
          title: '연락 스타일',
          question: '연락은 어느 정도 주고받는 게 좋나요?',
          type: MissionType.choice,
          choices: ['수시로', '자주', '적당히', '필요할 때만'],
          rewardTrustScore: 1,
          icon: '📱',
        ),
        DailyMission(
          day: 29,
          category: '연애관',
          title: '결혼관',
          question: '결혼에 대해 어떻게 생각하시나요?',
          type: MissionType.choice,
          choices: ['빨리 하고 싶다', '언젠가는', '아직 모르겠다', '계획 없음'],
          rewardTrustScore: 1,
          icon: '💍',
        ),
        DailyMission(
          day: 30,
          category: '특별 미션',
          title: '30일 완성!',
          question: '30일 챌린지를 완료했습니다! 이제 어떤 인연을 만나고 싶으신가요?',
          placeholder: '자유롭게 작성해주세요',
          type: MissionType.text,
          rewardTrustScore: 10,
          rewardTemperature: 3.0,
          icon: '🎆',
        ),
      ];
}
